"""Constants for the Ksenia Lares Alarm integration."""

DOMAIN = "ksenia_lares"
MANUFACTURER = "KSENIA"
DEFAULT_TIMEOUT = 10

DATA_ZONES = "ZONES"
DATA_PARTITIONS = "PARTITIONS"

ZONE_STATUS_ALARM = "ALARM"
ZONE_STATUS_NORMAL = "NORMAL"
ZONE_STATUS_NOT_USED = "NOT_USED"

ZONE_BYPASS_OFF = "UN_BYPASS"
ZONE_BYPASS_ON = "BYPASS"

PARTITION_STATUS_DISARMED = "DISARMED"
PARTITION_STATUS_ARMED = "ARMED"
PARTITION_STATUS_ARMED_IMMEDIATE = "ARMED_IMMEDIATE"
PARTITION_STATUS_ARMING = "EXIT"
PARTITION_STATUS_PENDING = "PREALARM"
PARTITION_STATUS_ALARM = "ALARM"

CONF_PARTITION_AWAY = "partition_away"
CONF_PARTITION_HOME = "partition_home"
CONF_PARTITION_NIGHT = "partition_night"

DATA_COORDINATOR = "coordinator"
DATA_UPDATE_LISTENER = "update_listener"
